# Load routing
iad_training:
    resource: "@IadTrainingBundle/Resources/config/routing.yml"
    prefix:   /

# Init email send service
iad_app_mail_send:
    path: /mails/send_mail
    defaults: { _controller: IadTrainingBundle:MyService:sendMail }

# Init app mail status
iad_app_mail_status:
    path: /mails/{id}/status
    defaults:  { _controller: IadTrainingBundle:MyService:getStatus }
    requirements:
        _method: GET
        id: \d+